### ISSUE TITLE
文档面包屑能否显示笔记本层级

### ISSUE THREAD

**Issue by liao-zh** [OpaqueGlass/syplugin-hierarchyNavigate#61]
希望能加个设置按钮，让笔记本层级优先在文档面包屑显示。
如果同时开启文档面包屑和文档信息行，那么笔记本在面包屑中显示，在信息行中不显示。

**Comment by OpaqueGlass** [comment]
我暂无计划调整层级导航插件中的面包屑相关功能，对于此需求，请考虑使用“（伪）文档面包屑”插件；

信息行中各项信息均有对应的span，并有独立的class区分，如果需要隐藏，可以考虑自定义css，例：

```css
.og-hierachy-navigate-info-container .og-hn-notebook-wrapper {
    display: none;
}

```

感谢反馈，此issue将被关闭。
