### ISSUE TITLE
上一篇、下一篇在文末显示，像trilium在文末lcd预览方格模式；

### ISSUE THREAD

**Issue by OpaqueGlass** [OpaqueGlass/syplugin-hierarchyNavigate#86]
- [x] 支持插入到文档结尾；（暂时不处理和其他插件的顺序冲突）
- [x] 带预览的上一篇、下一篇内容区；
- [x] 预览方格内容区

**Comment by Achuan-2** [comment]
太强了，非常美观且实用，给大佬点赞

![Image](https://github.com/user-attachments/assets/f65c31fc-b356-4273-8a8a-866c06666f6f)

**Comment by OpaqueGlass** [comment]
感谢支持~

下个版本还会再修改一些样式问题，现在没有对齐

**Comment by Achuan-2** [comment]
预览方格内容区建议上方能添加一个“子文档预览”文字，明确功能

**Comment by Achuan-2** [comment]
末尾前面最好添加一个分割线

![Image](https://github.com/user-attachments/assets/8201638e-dea9-491b-8142-db2bd524d408)


```css
.og-hn-heading-docs-container.og-hn-at-doc-end {
  border-top: 3px dashed var(--b3-border-color);
}
```

![Image](https://github.com/user-attachments/assets/007f6df9-df8c-4be4-aa5c-ba7b88b0a8bb)
